### ISSUE TITLE
Invest-a-Bowl mislabelled confusion

### ISSUE THREAD

**Issue by Jemsterr** [Slimmmo/Slimmmo.github.io#141]
The Hypno Ads and Designer Uniforms are labelled backwards.
The confusion comes because they boost each other instead of themselves.

![image](https://user-images.githubusercontent.com/17609227/35776929-709cd062-09f9-11e8-8d72-c13746fdf85d.png)

**Comment by 61352151511** [comment]
I believe this was fixed. Comment if it was not.

**Comment by Jemsterr** [comment]
It's a moot point now, but still incorrect.  (the numbers are fine, we're just told to upgrade the wrong one each time)
![image](https://user-images.githubusercontent.com/17609227/35831792-13d6e7b0-0b1f-11e8-9d22-dc4f148ee0f5.png)

**Comment by Nutty69** [comment]
I'll happily confirm this issue. Lines 1808 and 1809 in main.js should be flipped around. Added corrections in PR #147

**Comment by Slimmmo** [comment]
Merged, should be fixed.
